from .advanced_cnn import get_compiled_and_built_advanced_cnn
from .lenet5 import get_compiled_and_built_lenet
from .miscellaneous import variance, count_weights, current_accuracy, average_client_weights, synchronize_clients